[package]
name = "bgesav"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.20.1"
libbgesav = { path = "libbgesav" }
rfd = "0.11.0"

[workspace]
members = ["libbgesav"]
