pub const NAMES: [&str; 50] = [
    "Unknown",
    "Camera",
    "Cutting Pliers",
    "Fuse",
    "Materia Crystal",
    "Dai-jo",
    "Unknown",
    "City-pass",
    "Unknown",
    "Unknown (lightsaber handle model)",
    "Unknown (gem model)",
    "Gyrodisk launcher",
    "Mirror",
    "Flight stabilizer",
    "Unknown (Starkos sprite)",
    "Mecha Impulser",
    "P-O-D",
    "Set of Pods",
    "Room 03 ticket",
    "Animal detector",
    "Pearl detector",
    "Unknown",
    "Triangular key",
    "Square key",
    "Box of K-bups",
    "Star Key",
    "Armor",
    "Pey'j mdisk (for jade)",
    "Unknown",
    "PA 1",
    "Jet-boots",
    "Starkos",
    "Super-attack strengthened",
    "Unknown (empty sprite&model)",
    "Unknown (empty sprite&model)",
    "Unknown",
    "Carlson-Peeters",
    "Jump kit",
    "Boost",
    "Neutralizing Cannon",
    "Unknown (stellar engine sprite)",
    "Unknown (speedcraft motor sprite)",
    "Speedcraft Motor",
    "Compass",
    "Stellar Motor",
    "Unknown (empty sprite)",
    "Pearls (inventory item)",
    "Unknown",
    "Unknown",
    "Unknown",
];
