pub const CHARSET: [u8; 36] = [
    b'A', b'B', b'C', b'D', b'E', b'F', b'G', b'H', b'I', b'J', b'K', b'L', b'M', b'N', b'O', b'P',
    b'Q', b'R', b'S', b'T', b'U', b'V', b'W', b'X', b'Y', b'Z', b'0', b'1', b'2', b'3', b'4', b'5',
    b'6', b'7', b'8', b'9',
];

// Source: <https://gist.github.com/ItsYogSothoth/2d80f9b1acb6d54f0c8401cb226b3b4e>
pub const NAMES: [&str; 30] = [
    "Shoe code (left)",
    "Unknown",
    "Factory entrance",
    "Shoe code (right)",
    "Factory locker",
    "Moon transmiter",
    "Factory boss room",
    "Slaughterhouse exit",
    "Alpha Section locker (Pedestrian District)",
    "Rufus' room",
    "Unknown",
    "Unknown",
    "Room 03",
    "Disc game MDisk",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
];
